version: '3.8'

services:
  consul:
    image: consul:latest
    restart: on-failure
    networks:
      - lan
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
  postgres:
    image: postgres:latest
    restart: on-failure
    networks:
      - lan
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    volumes:
      - "./pg_data:/var/lib/postgresql/data/"
  prometheus:
    image: "prom/prometheus:v2.24.0"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
  grafana:
    image: "grafana/grafana"
    networks:
      - lan
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    restart: on-failure
    volumes:
      - "./tmp/build/grafana:/var/lib/grafana:cached"

networks:
  lan: